[tool.poetry]
name = "testTemplate"
version = "0.3.1"
description = ""
authors = ["BurnySc2 <gamingburny@gmail.com>"]
packages = [
    { include = "testTemplate/*.py" },
#    { include = "testTemplate/*.txt" },
]


[tool.poetry.dependencies]
python = ">=3.7, <3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
